name: Build & Publish All Artifacts

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      OWNER: shitcoderskpi

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore & Build all projects
      run: |
        cd src
        dotnet restore
        dotnet build --configuration Release

    - name: Create artifacts folder
      run: mkdir -p "$GITHUB_WORKSPACE/artifacts/nuget"

    - name: Pack all .csproj
      run: |
        for proj in $(find . -name '*.csproj'); do
          echo "→ Packing $proj"
          dotnet pack "$proj" \
            --configuration Release \
            --output "$GITHUB_WORKSPACE/artifacts/nuget"
        done

    - name: Push NuGet packages
      if: ${{ always() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -d "$GITHUB_WORKSPACE/artifacts/nuget" ] && ls "$GITHUB_WORKSPACE/artifacts/nuget"/*.nupkg 1> /dev/null 2>&1; then
          for pkg in "$GITHUB_WORKSPACE/artifacts/nuget"/*.nupkg; do
            echo "→ Pushing $pkg"
            dotnet nuget push "$pkg" \
              --source "https://nuget.pkg.github.com/$OWNER/index.json" \
              --api-key $GITHUB_TOKEN \
              --skip-duplicate
          done
        else
          echo "No NuGet packages found, skipping push."
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Build & Publish all JS packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for dir in $(find . -type f -name 'package.json' \
                      -not -path './node_modules/*' \
                      -printf '%h\n' | sort -u); do
          echo "→ Processing JS in $dir"
          cd "$dir"

          npm install
          npm run build
          npm publish --access public

          cd - > /dev/null
        done
